kind: pipeline
name: default

steps:

- name: restore-cache
  image: drillster/drone-volume-cache
  settings:
    restore: true
    mount:
      - ~/.cache/pip
  volumes:
  - name: cache
    path: /cache

- name: test
  image: python
  commands:
  - pip install -r requirements.txt
  - black .
  - env
  - pwd
  - ls -al ~/.cache

# - name: format
#   image: appleboy/drone-git-push
#   settings:
#     branch: master
#     remote: https://github.com/FLT4613/drone-test.git
#     force: false
#     commit: true
#     commit_message: "[skip ci] AutoFormat"



- name: rebuild-cache
  image: drillster/drone-volume-cache
  settings:
    rebuild: true
    mount:
      - ~/.cache/pip
  volumes:
  - name: cache
    path: /cache
  commands:
  - ls -al ~